apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: utilityemissions-api
  namespace: fabric-production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path:
        backend:
          serviceName: utilityemissions-api
          servicePort: 80  
