apiVersion: v1
kind: Service
metadata:
  name: utilityemissions-api
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 9000
    - name: https
      port: 443
      targetPort: 9000
  selector:
    app: utilityemissions-api
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: utilityemissions-api
  labels:
    app: utilityemissions-api
spec:
  selector:
    matchLabels:
      app: utilityemissions-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: utilityemissions-api
    spec:
      containers:
        - name: utilityemissions-api
          image: krybalko/utilityemissions-api:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
